[package]
name = "clap-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clap_repl"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
console = "0.15.7"
rustyline = "11.0.0"
shlex = "1.1.0"

[dev-dependencies]
redis = "0.23.0"
