[package]
name = "clap-repl"
description = "Build nice REPLs using clap and reedline with zero effort"
version = "0.3.2"
edition = "2024"
rust-version = "1.85"
homepage = "https://github.com/HKalbasi/clap-repl"
repository = "https://github.com/HKalbasi/clap-repl"
documentation = "https://docs.rs/clap-repl"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "clap_repl"
path = "src/lib.rs"

[features]
default = []
async = []

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
clap_complete = { version = "=4.6.7", features = ["unstable-dynamic"] }
console = "0.16.4"
nu-ansi-term = "0.50.3"
reedline = "0.49.0"
shlex = "2.0.1"

[dev-dependencies]
redis = "1.2.2"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "async"
required-features = ["async"]
